version: '3.8'

services:
  model_service:
    build: ./model_service
    ports:
      - "8000:8000"
    volumes:
      - ./checkpoint.pt:/app/checkpoint.pt
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  client_service:
    build: ./client_service
    ports:
      - "8001:8001"
    depends_on:
      - model_service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped 